# -*- coding: utf-8 -*-
{
    'name': 'Usl Field Service',
    'version': '2.0.0',
    'summary': 'Usl Field Service',
    'sequence': -100,
    'description': """Usl Field Service""",
    'category': 'Usl Field Service',
    'author': 'Unisoft Software Ltd',
    'maintainer': 'Unisoft Software Ltd',
    'website': 'https://uslbd.com/',
    'license': 'AGPL-3',
    'depends': ['mail', 'stock', 'product', 'gts_branch_management', 'gts_financial_pdf_report'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/data.xml',
        'views/menu.xml',

        'views/field_service_data_view.xml',
        'views/service_type_setup_view.xml',
        'views/warranty_void_reason_view.xml',
        'views/warranty_status_view.xml',
        'views/service_order_transfer_view.xml',
        'views/repair_status_view.xml',
        'views/assign_engineer_details.xml',
        'views/assign_engineer.xml',
        'views/template.xml',
        'views/engineer_observation.xml',
        'views/symptoms_type_view.xml',
        'views/field_service_department_view.xml',
        'views/field_service_priority_level_view.xml',
        'views/communication_media_view.xml',

        'views/service_order_transfer_view.xml',
        'views/css_loader.xml',
        'views/operation_receive.xml',

        'views/reason_type_view.xml',
        'views/item_requisition_inherit_view.xml',
        'views/advance_item_requisition_inherit_view.xml',
        'views/engineer_item_return_inherit_view.xml',
        'views/after_delivery_consumption_view.xml',
        'views/diagnosis_repair.xml',
        'views/warehouse_mapping_view.xml',
        'views/transfer_order_receive.xml',
        'views/transfer_order_receive_operation.xml',
        'views/service_type_setup_view.xml',
        'views/service_type_view.xml',
        'views/ready_for_replacement_view.xml',
        'views/item_consumption_view.xml',
        'views/service_order_receive.xml',
        'views/field_service_delivery_view.xml',
        'views/field_service_view.xml',
        'views/field_service_inherit_view.xml',
        'views/quality_assurance_details_view.xml',
        'views/quality_check_list_view.xml',
        'views/so_approval_config_view.xml',
        'views/invoice_approval_view.xml',
        'views/for_invoice_approval.xml',
        'views/non_serial_product_receive_from_customer_view.xml',
        'views/non_serial_product_delivery_view.xml',
        'views/non_serial_product_status_view.xml',
        'views/remarks_history_view.xml',
        'views/user_department_view.xml',
        'views/stock_location_inherit_view.xml',
        'views/nsp_claim.xml',
        'views/nsp_sales_return.xml',
        'views/nsp_approval_config.xml',
        'views/field_service_monitoring_data_view.xml',
        'views/field_service_monitoring_report_view.xml',

        'views/service_charge_claim_view.xml',
        'report/invoice_inherit_views.xml',
        'report/service_order_transfer_report_template.xml',
        'report/report.xml',
        'report/report_invoice_template.xml',
        'report/report_field_service_report_template.xml',

        # 'views/serviceChargeClaim_view.xml',
        'views/claimMnagement_view.xml',
        'views/ServiceChargeClaim_approval.xml',
        'views/brand_views.xml',
        'views/products_inherit.xml',
        # 'views/NonSerialproductLabour_claim.xml',
        'views/service_charge_claim_view.xml',
        'views/receive_approval_config.xml',
        'views/transfer_confirm_approval_config.xml',

    ],
    'assets': {
        'web.assets_backend': [
            '/usl_service_erp/static/src/css/style.css',
        ]},
    'demo': [],
    'qweb': [],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
