from . import serviceOrder
from . import fieldServiceData
from . import serviceType
from . import warrantyVoidReason
from . import symptomsType
from . import fieldServiceDepartment
from . import fieldServicePriorityLavel
from . import warrantyStatus
from . import communicationMedia
from . import assign_engineer
from . import assign_engineer_details
from . import diagnosis_repair

from . import order_item_receive
from . import item_receive
from . import engineer_observation
from . import stock_move
from . import itemRequisitionInherit
from . import advanceItemRequisitionInherit
from . import warehouse_mapping
from . import repair_status
from . import service_type_setup
from . import item_consumption
from . import quality_assurance_details
from . import qa_check_list
from . import fieldServiceDelivery
from . import item_consumption_inherit
from . import so_approval_config
from . import invoice_approval
from . import engineer_item_return_inherit
from . import for_invoice_approval
from . import non_serial_product_receive_from_customer
from . import non_serial_product_delivery
from . import remarks_history
from . import nsp_claim
from . import nsp_approval_config
from . import nsp_sales_return
from . import field_service_monitoring_data
from . import field_service_monitoring_report
from . import xls_report_tool
from . import non_serial_product_status
from . import service_charge_claim
from . import claimManagement
from . import products_inherit
from . import  ServiceChargeClaim_approval
from . import TransferReceiveApproval_config
from . import serial_product_part_claim
